force-app/main/default/objects/Expense_Tracker__c/Expense_Tracker__c.object-meta.xml
<CustomObject>
    <label>Expense Tracker</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>Expense Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Tracker__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense_Tracker__c/fields/Expense_Category__c.field-meta.xml
<CustomField>
    <fullName>Expense_Category__c</fullName>
    <label>Expense Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Education Expenses</fullName>
            </value>
            <value>
                <fullName>Gifts and Donations</fullName>
            </value>
            <value>
                <fullName>Healthcare Expenses</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Transportation Expenses</fullName>
            </value>
            <value>
                <fullName>Travel Expenses</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Tracker__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Tracker__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ExpenseTrackerController.cls
public with sharing class ExpenseTrackerController {
    
    @AuraEnabled
    public static void saveRecords(List<Map<String, Object>> records, String[] toDeleteRecordIds) {
        List<Expense_Tracker__c> expenseTrackers = new List<Expense_Tracker__c>();
        
        for (Map<String, Object> record : records) {
            Expense_Tracker__c expensetracker = new Expense_Tracker__c();
            String rowId = (String) record.get('Id');
            if(!String.isBlank(rowId) && !rowId.toUpperCase().startsWith('ROW')){
                expensetracker.Id = (String) record.get('Id');
            }
            if(!String.isBlank((String) record.get('Expense_Date__c'))){
                String isoDate = (String) record.get('Expense_Date__c');
                expensetracker.Expense_Date__c = parseIsoDate(isoDate);
            }
            if(!String.isBlank((String) record.get('Expense_Category__c'))){
                expensetracker.Expense_Category__c = (String) record.get('Expense_Category__c');
            } 
            if(!String.isBlank(String.valueOf(Integer.valueOf(record.get('Amount__c'))))){
                expensetracker.Amount__c = Integer.valueOf(record.get('Amount__c'));
            }
            if(!String.isBlank((String) record.get('Remarks__c'))){
                expensetracker.Remarks__c = (String) record.get('Remarks__c');
            }
            if(!String.isBlank((String) record.get('expense_claim_name'))){
                expensetracker.Expense_Claim_Name__c = (String) record.get('expense_claim_name');
            }
            expenseTrackers.add(expensetracker);
        }
        if (!expenseTrackers.isEmpty()) {
            upsert expenseTrackers;
        }

        if(!toDeleteRecordIds.isEmpty()){
            List<Expense_Tracker__c> expenserecordstodelete = [SELECT Id FROM Expense_Tracker__c WHERE Id IN : toDeleteRecordIds];
            delete expenserecordstodelete;
        }
    }

    @AuraEnabled(Cacheable=true)
    public static List<Expense_Tracker__c> getRecords(String expenseClaimName) {
            return [SELECT Id, Expense_Date__c, Expense_Category__c, Remarks__c, Amount__c FROM Expense_Tracker__c WHERE Expense_Claim_Name__c = :expenseClaimName];
    }

    @AuraEnabled(Cacheable = true)
    public static List<Expense_Activity__mdt> getExpenseActivityOptions(){
        return [SELECT Id,DeveloperName,Label FROM Expense_Activity__mdt];
    }

    public static Date parseIsoDate(String isoDate) {
        if (String.isBlank(isoDate)) {
            return null;
        }
        String[] splits = isoDate.split('-');
        System.debug('Date splitted:' + splits[0] + splits[1] + splits[2]);
        System.debug(Date.newInstance(Integer.valueOf(splits[0]), Integer.valueOf(splits[1]), Integer.valueOf(splits[2])));
        return Date.newInstance(Integer.valueOf(splits[0]), Integer.valueOf(splits[1]), Integer.valueOf(splits[2]));
    }
}